level 4.3.2560

diff --git a/src/build/install/resources/cflash_version b/src/build/install/resources/cflash_version
--- a/src/build/install/resources/cflash_version
+++ b/src/build/install/resources/cflash_version
@@ -27,9 +27,6 @@
 if [[ $1 =~ help || $1 =~ -h ]]; then echo "Usage: $(basename $0)"; exit 0; fi
 if [[ $1 =~ version ]]; then echo "v1.0"; exit 0; fi
 
-# check permissions
-if [[ $(id -u) != 0 ]]; then echo "use sudo"; exit 1; fi
-
 export PATH=$PATH:/usr/bin
 
 #determine distro
@@ -132,12 +129,20 @@ then
   n2=$(echo $EXISTS_GRUB_VER|awk -F. '{print $2}')
   n3=$(echo $EXISTS_GRUB_VER|awk -F. '{print $3}'|awk -F- '{print $1}')
   n4=$(echo $EXISTS_GRUB_VER|awk -F- '{print $2}'|awk -F. '{print $1}')
-  if [[ ($n1 -lt 4) ||
-        ($n1 -eq 4 && $n2 -lt 4) ||
-        ($n1 -eq 4 && $n2 -eq 4 && $n3 -eq 0 && $n4 -lt 36) ]]
+  if [[ ! -z ${EXISTS_GRUB_VER} &&
+        (($n1 -lt 4) ||
+         ($n1 -eq 4 && $n2 -lt 4) ||
+         ($n1 -eq 4 && $n2 -eq 4 && $n3 -eq 0 && $n4 -lt 36)) ]]
   then
     err_rc=6
     echo "ERROR:     Grub:          grub.cfg($EXISTS_GRUB_VER) => Required($K_VER_GRUB) or newer"
+  fi
+
+  #check permissions
+  if [[ ! ($(groups ${USER}) =~ cxl || $(id -u ${USER}) -eq 0) ]]
+  then
+    echo "You do not have enough permissions to check the firmware levels"
+    exit $err_rc
   fi
 
  if [[ -e /usr/bin/capi_flash ]]
@@ -229,22 +234,31 @@ then
     echo "ERROR:     cxlflash-test: Installed($EXISTS_CF_TEST_VER) != Required($CF_VER)"
   fi
 
-  EXISTS_K_VER=$(rpm -q kernel)
-  if [[ ! $EXISTS_K_VER =~ $K_VER ]]
+  EXISTS_K_VER=$(rpm -qa|grep $(uname -a|awk '{print $3}')|awk -Fkernel- '{print $2}')
+  n1=$(echo $EXISTS_K_VER|awk -F. '{print $1}')
+  n2=$(echo $EXISTS_K_VER|awk -F. '{print $2}')
+  if [[ ($n1 -lt 3) || ($n1 -eq 3 && $n2 -lt 10) ]]
   then
-    err_rc=5
-    echo "WARNING:   Kernel:        Booted($(uname -a|awk '{print $3}')) != Required($K_VER)"
+      err_rc=5
+      echo "ERROR:     Kernel:        Booted($EXISTS_K_VER) => Required($K_VER) or newer"
   else
-    echo "INFO:      Kernel:        $K_VER"
+    echo   "INFO:      Kernel:        $EXISTS_K_VER"
   fi
 
-  EXISTS_GRUB_VER=$(grep initrd /boot/grub2/grub.cfg  | head -1 | awk -Finitramfs- '{print $2}')
+  EXISTS_GRUB_VER=$(grep initrd /boot/grub2/grub.cfg 2>/dev/null| head -1 | awk -Finitramfs- '{print $2}')
   n1=$(echo $EXISTS_GRUB_VER|awk -F. '{print $1}')
   n2=$(echo $EXISTS_GRUB_VER|awk -F. '{print $2}')
-  if [[ ($n1 -lt 3) || ($n1 -eq 3 && $n2 -lt 10) ]]
+  if [[ ! -z ${EXISTS_GRUB_VER} && (($n1 -lt 3) || ($n1 -eq 3 && $n2 -lt 10)) ]]
   then
     err_rc=6
     echo "WARNING:   Grub:          grub.cfg($EXISTS_GRUB_VER) != Required($K_VER_GRUB)"
+  fi
+
+  #check permissions
+  if [[ ! ($(groups ${USER}) =~ cxl || $(id -u ${USER}) -eq 0) ]]
+  then
+    echo "You do not have enough permissions to check the firmware levels"
+    exit $err_rc
   fi
 
   if [[ -e /usr/bin/capi_flash ]]
